FROM apache/kafka:3.9.1
ADD --checksum=sha256:ba74aad73934e59f4ca9c0779b49f1663c1fc7a81d5d99fc665bd5e5039310f5 --chmod=755 https://github.com/prometheus/jmx_exporter/releases/download/1.3.0/jmx_prometheus_javaagent-1.3.0.jar /opt/metrics/jmx.jar
COPY monitoring/exporters/jmx.yml /opt/metrics/jmx.yml

USER root
RUN mv /opt/kafka/bin/kafka-server-start.sh /opt/kafka/bin/kafka-server-start-original.sh
COPY --chmod=755 monitoring/exporters/start-kafka.sh /opt/kafka/bin/kafka-server-start.sh
USER appuser
