"""Frozen v1 DDL shared by four independent Alembic histories. Do not edit after release."""

from alembic import op


def statements(sql: str):
    for statement in sql.split(";"):
        if statement.strip():
            op.execute(statement)


def upgrade_common():
    statements("""
    CREATE TABLE outbox_events (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        aggregate_id VARCHAR(128) NOT NULL,
        event_id UUID NOT NULL UNIQUE,
        event_type VARCHAR(100) NOT NULL,
        topic VARCHAR(100) NOT NULL,
        payload JSONB NOT NULL,
        status VARCHAR(20) NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING','PUBLISHED')),
        attempts INTEGER NOT NULL DEFAULT 0,
        last_error TEXT,
        created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        next_attempt_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        published_at TIMESTAMPTZ
    );
    CREATE INDEX ix_outbox_pending ON outbox_events (next_attempt_at, id) WHERE status = 'PENDING';
    CREATE INDEX ix_outbox_aggregate ON outbox_events (aggregate_id, id) WHERE status = 'PENDING';
    CREATE TABLE processed_events (
        event_id UUID NOT NULL,
        consumer_name VARCHAR(100) NOT NULL,
        processed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        PRIMARY KEY (event_id, consumer_name)
    );
    CREATE TABLE idempotency_records (
        scope VARCHAR(100) NOT NULL,
        key_hash VARCHAR(64) NOT NULL,
        request_hash VARCHAR(64) NOT NULL,
        response JSONB,
        status_code INTEGER NOT NULL DEFAULT 201,
        created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        PRIMARY KEY (scope, key_hash),
        CONSTRAINT uq_idempotency_scope_key UNIQUE (scope, key_hash)
    );
    """)


def downgrade_common():
    statements(
        "DROP TABLE idempotency_records; DROP TABLE processed_events; DROP TABLE outbox_events;"
    )
