-- =============================================================================
-- E-commerce schema
--
--   users ─┬─< addresses
--          ├─< orders ─┬─< order_items >── products
--          │           └─< payments
--          └─< reviews >── products
--   categories ─< categories (parent/child)
--   categories ─< products ─┬─< inventory >── warehouses
--                           ├─< order_items
--                           └─< reviews
--
-- Conventions
--   * bigint identity primary keys (GENERATED BY DEFAULT so the bulk loader can
--     supply ids; sequences are re-synced after the load)
--   * money = numeric(12,2)   (never float for money)
--   * time  = timestamptz     (stored as UTC instant)
--   * named constraints (pk_/fk_/uq_/ck_) so error messages are readable
--   * Indexes live in 04-indexes.sql (only the ones created implicitly by
--     PRIMARY KEY / UNIQUE constraints appear here)
-- =============================================================================

-- -----------------------------------------------------------------------------
-- Enumerated types (ordered! 'PENDING' < 'CONFIRMED' < ... in comparisons/sorts)
-- -----------------------------------------------------------------------------
CREATE TYPE user_status    AS ENUM ('ACTIVE', 'INACTIVE', 'SUSPENDED', 'DELETED');
CREATE TYPE address_label  AS ENUM ('HOME', 'WORK', 'OTHER');
CREATE TYPE product_status AS ENUM ('DRAFT', 'ACTIVE', 'OUT_OF_STOCK', 'DISCONTINUED');
CREATE TYPE order_status   AS ENUM ('PENDING', 'CONFIRMED', 'PROCESSING', 'SHIPPED', 'COMPLETED', 'CANCELLED');
CREATE TYPE payment_method AS ENUM ('CREDIT_CARD', 'DEBIT_CARD', 'E_WALLET', 'BANK_TRANSFER', 'COD', 'PAYPAL');
CREATE TYPE payment_status AS ENUM ('PENDING', 'SUCCEEDED', 'FAILED', 'REFUNDED');

-- -----------------------------------------------------------------------------
-- Trigger function: keep updated_at current on UPDATE
-- -----------------------------------------------------------------------------
CREATE FUNCTION set_updated_at() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$;

-- -----------------------------------------------------------------------------
-- users
-- -----------------------------------------------------------------------------
CREATE TABLE users (
  id                 bigint       GENERATED BY DEFAULT AS IDENTITY,
  username           varchar(50)  NOT NULL,
  email              varchar(255) NOT NULL,
  password_hash      text         NOT NULL,
  full_name          varchar(150) NOT NULL,
  phone              varchar(30),
  date_of_birth      date,
  gender             char(1),
  status             user_status  NOT NULL DEFAULT 'ACTIVE',
  is_email_verified  boolean      NOT NULL DEFAULT false,
  loyalty_points     integer      NOT NULL DEFAULT 0,
  last_login_at      timestamptz,
  last_login_ip      inet,
  metadata           jsonb        NOT NULL DEFAULT '{}'::jsonb,
  created_at         timestamptz  NOT NULL DEFAULT now(),
  updated_at         timestamptz  NOT NULL DEFAULT now(),

  CONSTRAINT pk_users PRIMARY KEY (id),
  CONSTRAINT uq_users_username UNIQUE (username),
  CONSTRAINT ck_users_email_format CHECK (email ~* '^[^@\s]+@[^@\s]+\.[^@\s]+$'),
  CONSTRAINT ck_users_gender CHECK (gender IN ('M', 'F', 'O')),
  CONSTRAINT ck_users_loyalty_points CHECK (loyalty_points >= 0),
  CONSTRAINT ck_users_metadata_is_object CHECK (jsonb_typeof(metadata) = 'object')
);
-- Email uniqueness is case-insensitive -> enforced by the UNIQUE expression
-- index ux_users_email_lower in 04-indexes.sql (a constraint cannot do that).
COMMENT ON TABLE  users IS 'Customer accounts';
COMMENT ON COLUMN users.metadata IS 'Free-form profile data: signup_source, preferred_language, marketing_opt_in, tags, preferences...';

CREATE TRIGGER trg_users_updated_at BEFORE UPDATE ON users
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- -----------------------------------------------------------------------------
-- addresses (1..n per user, at most one default)
-- -----------------------------------------------------------------------------
CREATE TABLE addresses (
  id              bigint        GENERATED BY DEFAULT AS IDENTITY,
  user_id         bigint        NOT NULL,
  label           address_label NOT NULL DEFAULT 'HOME',
  recipient_name  varchar(150)  NOT NULL,
  phone           varchar(30),
  line1           varchar(255)  NOT NULL,
  line2           varchar(255),
  city            varchar(100)  NOT NULL,
  state           varchar(100),
  postal_code     varchar(20),
  country_code    char(2)       NOT NULL DEFAULT 'US',
  is_default      boolean       NOT NULL DEFAULT false,
  created_at      timestamptz   NOT NULL DEFAULT now(),

  CONSTRAINT pk_addresses PRIMARY KEY (id),
  CONSTRAINT fk_addresses_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
  CONSTRAINT ck_addresses_country_code CHECK (country_code ~ '^[A-Z]{2}$')
);
COMMENT ON TABLE addresses IS 'Address book. "One default per user" is enforced by a partial unique index.';

-- -----------------------------------------------------------------------------
-- categories (two-level tree via self reference)
-- -----------------------------------------------------------------------------
CREATE TABLE categories (
  id           integer      GENERATED BY DEFAULT AS IDENTITY,
  parent_id    integer,
  name         varchar(100) NOT NULL,
  slug         varchar(120) NOT NULL,
  description  text,
  is_active    boolean      NOT NULL DEFAULT true,
  sort_order   smallint     NOT NULL DEFAULT 0,
  created_at   timestamptz  NOT NULL DEFAULT now(),

  CONSTRAINT pk_categories PRIMARY KEY (id),
  CONSTRAINT fk_categories_parent FOREIGN KEY (parent_id) REFERENCES categories (id) ON DELETE RESTRICT,
  CONSTRAINT uq_categories_slug UNIQUE (slug),
  -- NULLS NOT DISTINCT (PG15+): two top-level categories (parent_id NULL) cannot share a name
  CONSTRAINT uq_categories_parent_name UNIQUE NULLS NOT DISTINCT (parent_id, name),
  CONSTRAINT ck_categories_not_own_parent CHECK (parent_id IS NULL OR parent_id <> id)
);

-- -----------------------------------------------------------------------------
-- products
-- -----------------------------------------------------------------------------
CREATE TABLE products (
  id              bigint         GENERATED BY DEFAULT AS IDENTITY,
  category_id     integer        NOT NULL,
  sku             varchar(32)    NOT NULL,
  name            varchar(255)   NOT NULL,
  description     text,
  brand           varchar(100),
  price           numeric(12,2)  NOT NULL,
  cost            numeric(12,2)  NOT NULL,
  stock_quantity  integer        NOT NULL DEFAULT 0,
  status          product_status NOT NULL DEFAULT 'DRAFT',
  weight_grams    integer,
  tags            text[]         NOT NULL DEFAULT '{}',
  attributes      jsonb          NOT NULL DEFAULT '{}'::jsonb,
  created_at      timestamptz    NOT NULL DEFAULT now(),
  updated_at      timestamptz    NOT NULL DEFAULT now(),

  CONSTRAINT pk_products PRIMARY KEY (id),
  CONSTRAINT fk_products_category FOREIGN KEY (category_id) REFERENCES categories (id) ON DELETE RESTRICT,
  CONSTRAINT uq_products_sku UNIQUE (sku),
  CONSTRAINT ck_products_price CHECK (price >= 0),
  CONSTRAINT ck_products_cost CHECK (cost >= 0),
  CONSTRAINT ck_products_stock CHECK (stock_quantity >= 0),
  CONSTRAINT ck_products_weight CHECK (weight_grams IS NULL OR weight_grams > 0),
  CONSTRAINT ck_products_attributes_is_object CHECK (jsonb_typeof(attributes) = 'object')
);
COMMENT ON COLUMN products.stock_quantity IS 'Denormalised: SUM(inventory.quantity) across warehouses';

CREATE TRIGGER trg_products_updated_at BEFORE UPDATE ON products
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- -----------------------------------------------------------------------------
-- warehouses + inventory (stock per product per warehouse)
-- -----------------------------------------------------------------------------
CREATE TABLE warehouses (
  id            smallint     GENERATED BY DEFAULT AS IDENTITY,
  code          varchar(20)  NOT NULL,
  name          varchar(100) NOT NULL,
  city          varchar(100) NOT NULL,
  country_code  char(2)      NOT NULL,
  is_active     boolean      NOT NULL DEFAULT true,
  created_at    timestamptz  NOT NULL DEFAULT now(),

  CONSTRAINT pk_warehouses PRIMARY KEY (id),
  CONSTRAINT uq_warehouses_code UNIQUE (code)
);

CREATE TABLE inventory (
  id                 bigint      GENERATED BY DEFAULT AS IDENTITY,
  product_id         bigint      NOT NULL,
  warehouse_id       smallint    NOT NULL,
  quantity           integer     NOT NULL DEFAULT 0,
  reserved_quantity  integer     NOT NULL DEFAULT 0,
  reorder_level      integer     NOT NULL DEFAULT 10,
  last_restocked_at  timestamptz,
  updated_at         timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT pk_inventory PRIMARY KEY (id),
  CONSTRAINT fk_inventory_product FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE,
  CONSTRAINT fk_inventory_warehouse FOREIGN KEY (warehouse_id) REFERENCES warehouses (id) ON DELETE RESTRICT,
  CONSTRAINT uq_inventory_product_warehouse UNIQUE (product_id, warehouse_id),
  CONSTRAINT ck_inventory_quantity CHECK (quantity >= 0),
  CONSTRAINT ck_inventory_reserved CHECK (reserved_quantity >= 0 AND reserved_quantity <= quantity),
  CONSTRAINT ck_inventory_reorder_level CHECK (reorder_level >= 0)
);

CREATE TRIGGER trg_inventory_updated_at BEFORE UPDATE ON inventory
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- -----------------------------------------------------------------------------
-- orders
-- -----------------------------------------------------------------------------
CREATE TABLE orders (
  id                bigint        GENERATED BY DEFAULT AS IDENTITY,
  user_id           bigint        NOT NULL,
  order_number      varchar(20)   NOT NULL,
  status            order_status  NOT NULL DEFAULT 'PENDING',
  subtotal          numeric(12,2) NOT NULL,
  discount          numeric(12,2) NOT NULL DEFAULT 0,
  shipping_fee      numeric(12,2) NOT NULL DEFAULT 0,
  total_amount      numeric(12,2) NOT NULL,
  currency          char(3)       NOT NULL DEFAULT 'USD',
  coupon_code       varchar(30),
  shipping_address  jsonb         NOT NULL,
  note              text,
  created_at        timestamptz   NOT NULL DEFAULT now(),
  updated_at        timestamptz   NOT NULL DEFAULT now(),

  CONSTRAINT pk_orders PRIMARY KEY (id),
  CONSTRAINT fk_orders_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT,
  CONSTRAINT uq_orders_order_number UNIQUE (order_number),
  CONSTRAINT ck_orders_subtotal CHECK (subtotal >= 0),
  CONSTRAINT ck_orders_discount CHECK (discount >= 0 AND discount <= subtotal),
  CONSTRAINT ck_orders_shipping_fee CHECK (shipping_fee >= 0),
  CONSTRAINT ck_orders_total CHECK (total_amount = subtotal - discount + shipping_fee)
);
COMMENT ON COLUMN orders.shipping_address IS 'Snapshot of the address at checkout time (JSONB), not a FK: later address edits must not change old orders';

CREATE TRIGGER trg_orders_updated_at BEFORE UPDATE ON orders
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- -----------------------------------------------------------------------------
-- order_items
-- -----------------------------------------------------------------------------
CREATE TABLE order_items (
  id           bigint        GENERATED BY DEFAULT AS IDENTITY,
  order_id     bigint        NOT NULL,
  product_id   bigint        NOT NULL,
  quantity     integer       NOT NULL,
  unit_price   numeric(12,2) NOT NULL,
  discount     numeric(12,2) NOT NULL DEFAULT 0,
  total_price  numeric(12,2) NOT NULL,

  CONSTRAINT pk_order_items PRIMARY KEY (id),
  CONSTRAINT fk_order_items_order FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE,
  CONSTRAINT fk_order_items_product FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE RESTRICT,
  CONSTRAINT uq_order_items_order_product UNIQUE (order_id, product_id),
  CONSTRAINT ck_order_items_quantity CHECK (quantity > 0),
  CONSTRAINT ck_order_items_unit_price CHECK (unit_price >= 0),
  CONSTRAINT ck_order_items_discount CHECK (discount >= 0 AND discount <= quantity * unit_price),
  CONSTRAINT ck_order_items_total CHECK (total_price = quantity * unit_price - discount)
);
COMMENT ON COLUMN order_items.unit_price IS 'Price at purchase time (products.price may change later)';

-- -----------------------------------------------------------------------------
-- payments (0..n attempts per order)
-- -----------------------------------------------------------------------------
CREATE TABLE payments (
  id                 bigint         GENERATED BY DEFAULT AS IDENTITY,
  order_id           bigint         NOT NULL,
  payment_method     payment_method NOT NULL,
  amount             numeric(12,2)  NOT NULL,
  status             payment_status NOT NULL DEFAULT 'PENDING',
  transaction_id     uuid,
  provider_response  jsonb,
  paid_at            timestamptz,
  created_at         timestamptz    NOT NULL DEFAULT now(),

  CONSTRAINT pk_payments PRIMARY KEY (id),
  CONSTRAINT fk_payments_order FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE,
  -- UNIQUE allows many NULLs (PENDING payments have no transaction id yet)
  CONSTRAINT uq_payments_transaction_id UNIQUE (transaction_id),
  CONSTRAINT ck_payments_amount CHECK (amount > 0),
  -- money was captured  <=>  paid_at is set
  CONSTRAINT ck_payments_paid_at CHECK ((status IN ('SUCCEEDED', 'REFUNDED')) = (paid_at IS NOT NULL))
);

-- -----------------------------------------------------------------------------
-- reviews (one per user per product)
-- -----------------------------------------------------------------------------
CREATE TABLE reviews (
  id                    bigint       GENERATED BY DEFAULT AS IDENTITY,
  product_id            bigint       NOT NULL,
  user_id               bigint       NOT NULL,
  order_id              bigint,
  rating                smallint     NOT NULL,
  title                 varchar(200),
  body                  text,
  is_verified_purchase  boolean      NOT NULL DEFAULT false,
  helpful_count         integer      NOT NULL DEFAULT 0,
  created_at            timestamptz  NOT NULL DEFAULT now(),

  CONSTRAINT pk_reviews PRIMARY KEY (id),
  CONSTRAINT fk_reviews_product FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE,
  CONSTRAINT fk_reviews_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
  -- NOTE: reviews.order_id is intentionally NOT indexed (see docs/index-lab.md, "unindexed foreign key")
  CONSTRAINT fk_reviews_order FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE SET NULL,
  CONSTRAINT uq_reviews_user_product UNIQUE (user_id, product_id),
  CONSTRAINT ck_reviews_rating CHECK (rating BETWEEN 1 AND 5),
  CONSTRAINT ck_reviews_helpful_count CHECK (helpful_count >= 0)
  -- No CHECK "verified => order_id IS NOT NULL": it would contradict ON DELETE SET NULL
  -- (deleting an order must not be blocked by, or delete, its reviews).
);

-- -----------------------------------------------------------------------------
-- data_generator_runs: bookkeeping for the Python data generator
-- (a COMPLETED run makes the generator skip on the next `docker compose up`)
-- -----------------------------------------------------------------------------
CREATE TABLE data_generator_runs (
  id           integer     GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  status       text        NOT NULL CHECK (status IN ('RUNNING', 'COMPLETED', 'FAILED')),
  settings     jsonb       NOT NULL,
  row_counts   jsonb,
  error        text,
  -- index / UNIQUE / FK definitions dropped for the bulk load and not rebuilt yet
  -- (the next run re-creates them if the generator died half way)
  deferred_ddl jsonb,
  started_at   timestamptz NOT NULL DEFAULT now(),
  finished_at  timestamptz
);

-- -----------------------------------------------------------------------------
-- replication_test: scratch table used by scripts/replication-test.sh
-- -----------------------------------------------------------------------------
CREATE TABLE replication_test (
  id          bigint      GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  token       text        NOT NULL UNIQUE,
  note        text,
  created_at  timestamptz NOT NULL DEFAULT clock_timestamp()
);
